/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package psv;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.*;
import javax.swing.*;

public class JFUsuario extends javax.swing.JFrame {

    public JFUsuario() {
        initComponents();
        lblMensagemUsuario.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlCentral = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        lblCPF1 = new javax.swing.JLabel();
        lblMensagemUsuario = new javax.swing.JLabel();
        radioSim = new javax.swing.JRadioButton();
        radioNao = new javax.swing.JRadioButton();
        pnlBotoes = new javax.swing.JPanel();
        btnIncluirUsuario = new javax.swing.JButton();
        btnAlterarUsuario = new javax.swing.JButton();
        btnExcluirUsuario = new javax.swing.JButton();
        btnListarUsuario = new javax.swing.JButton();
        btnLimparUsuario = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        pnlConsultaUsuario = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbConsultaUsuario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        pnlTitulo.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 121, 145));
        lblTitulo.setText("Gerenciamento de Usuários");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo)
        );

        pnlCentral.setBackground(new java.awt.Color(204, 204, 204));

        lblNome.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblNome.setText("Nome:");

        txtNome.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblEmail.setText("E-mail:");

        txtEmail.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        lblSenha.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblSenha.setText("Senha:");

        txtSenha.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        lblCPF.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblCPF.setText("CPF:");

        txtCPF.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        lblCPF1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblCPF1.setText("Administrador:");

        lblMensagemUsuario.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblMensagemUsuario.setText("Mensagem");

        radioSim.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup.add(radioSim);
        radioSim.setText("Sim");
        radioSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSimActionPerformed(evt);
            }
        });

        radioNao.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup.add(radioNao);
        radioNao.setText("Não");
        radioNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCentralLayout = new javax.swing.GroupLayout(pnlCentral);
        pnlCentral.setLayout(pnlCentralLayout);
        pnlCentralLayout.setHorizontalGroup(
            pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCPF, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSenha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNome, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCPF1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCentralLayout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addComponent(radioNao)
                            .addGap(516, 516, 516)))
                    .addGroup(pnlCentralLayout.createSequentialGroup()
                        .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioSim)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(pnlCentralLayout.createSequentialGroup()
                .addGap(451, 451, 451)
                .addComponent(lblMensagemUsuario)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlCentralLayout.setVerticalGroup(
            pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSenha))
                .addGap(20, 20, 20)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCPF1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioSim)
                        .addComponent(radioNao)))
                .addGap(20, 20, 20)
                .addComponent(lblMensagemUsuario)
                .addGap(20, 20, 20))
        );

        pnlBotoes.setBackground(new java.awt.Color(204, 204, 204));

        btnIncluirUsuario.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnIncluirUsuario.setText("Incluir");
        btnIncluirUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIncluirUsuarioMouseClicked(evt);
            }
        });
        btnIncluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirUsuarioActionPerformed(evt);
            }
        });

        btnAlterarUsuario.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAlterarUsuario.setText("Alterar");
        btnAlterarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarUsuarioMouseClicked(evt);
            }
        });

        btnExcluirUsuario.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnExcluirUsuario.setText("Excluir");
        btnExcluirUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirUsuarioMouseClicked(evt);
            }
        });

        btnListarUsuario.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnListarUsuario.setText("Listar");
        btnListarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarUsuarioMouseClicked(evt);
            }
        });

        btnLimparUsuario.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnLimparUsuario.setText("Limpar");
        btnLimparUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimparUsuarioUsuarioMouseClicked(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlBotoesLayout = new javax.swing.GroupLayout(pnlBotoes);
        pnlBotoes.setLayout(pnlBotoesLayout);
        pnlBotoesLayout.setHorizontalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnIncluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlterarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimparUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pnlBotoesLayout.setVerticalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnlConsultaUsuario.setBackground(new java.awt.Color(204, 204, 204));

        tbConsultaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Nome", "Senha", "Email", "Administrador"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbConsultaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbConsultaUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbConsultaUsuario);
        if (tbConsultaUsuario.getColumnModel().getColumnCount() > 0) {
            tbConsultaUsuario.getColumnModel().getColumn(0).setResizable(false);
            tbConsultaUsuario.getColumnModel().getColumn(1).setResizable(false);
            tbConsultaUsuario.getColumnModel().getColumn(2).setResizable(false);
            tbConsultaUsuario.getColumnModel().getColumn(3).setResizable(false);
            tbConsultaUsuario.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout pnlConsultaUsuarioLayout = new javax.swing.GroupLayout(pnlConsultaUsuario);
        pnlConsultaUsuario.setLayout(pnlConsultaUsuarioLayout);
        pnlConsultaUsuarioLayout.setHorizontalGroup(
            pnlConsultaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnlConsultaUsuarioLayout.setVerticalGroup(
            pnlConsultaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlConsultaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlConsultaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        JFMenu jFMenu = new JFMenu ();
        jFMenu .setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarMouseClicked

    private void btnLimparUsuarioUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparUsuarioUsuarioMouseClicked
        // Limpando dados da janela
        txtNome.setText("");
        txtEmail.setText("");
        txtSenha.setText("");
        txtCPF.setText("");
        buttonGroup.clearSelection();
                
        lblMensagemUsuario.setText("");
        
        DefaultTableModel tbm = (DefaultTableModel) tbConsultaUsuario.getModel();
        
        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
            tbm.removeRow(i);
        }

    }//GEN-LAST:event_btnLimparUsuarioUsuarioMouseClicked

    private void btnIncluirUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIncluirUsuarioMouseClicked
        // Inserindo valores no banco de dados
        Connection con = Conexao.abrirConexao();
        UsuarioBean ub = new UsuarioBean();
        UsuarioDAO ud = new UsuarioDAO(con);
        
        ub.setNome(txtNome.getText());
        ub.setEmail(txtEmail.getText());
        ub.setSenha(txtSenha.getText());
        ub.setCPF(txtCPF.getText());
        
        if (radioSim.isSelected()) {
            ub.setAdministrador(true);
        } else {
            ub.setAdministrador(false);
        }
        
        lblMensagemUsuario.setText(ud.inserirUsuario(ub));
        
        Conexao.fecharConexao(con);

    }//GEN-LAST:event_btnIncluirUsuarioMouseClicked

    private void btnListarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarUsuarioMouseClicked
        // Pesquisando valores do banco de dados
        Connection con = Conexao.abrirConexao();
        
        UsuarioDAO ud = new UsuarioDAO(con);
        
        List<UsuarioBean> listaUsuario = new ArrayList<UsuarioBean>();
        
        listaUsuario = ud.listarTodos();
        
        DefaultTableModel tbm = (DefaultTableModel) tbConsultaUsuario.getModel();
        
        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
            tbm.removeRow(i);
        }
        
        int i = 0;
        
        for (UsuarioBean ub : listaUsuario) {
            tbm.addRow(new String[1]);
            
            tbConsultaUsuario.setValueAt(ub.getCPF(), i, 0);
            tbConsultaUsuario.setValueAt(ub.getNome(), i, 1);
            tbConsultaUsuario.setValueAt(ub.getSenha(), i, 2);
            tbConsultaUsuario.setValueAt(ub.getEmail(), i, 3);
            tbConsultaUsuario.setValueAt(ub.getAdministrador(), i, 4);

            i++;
        }
        
        Conexao.fecharConexao(con);
    
    }//GEN-LAST:event_btnListarUsuarioMouseClicked

    private void tbConsultaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbConsultaUsuarioMouseClicked
        // Passando os valores da linha da tabela para os campos

        Integer linha = tbConsultaUsuario.getSelectedRow();
        
        String cpf = (String) tbConsultaUsuario.getValueAt(linha, 0);
        String nome = (String) tbConsultaUsuario.getValueAt(linha, 1);
        String senha = (String) tbConsultaUsuario.getValueAt(linha, 2);
        String email = (String) tbConsultaUsuario.getValueAt(linha, 3);
        boolean administrador = (Boolean) tbConsultaUsuario.getValueAt(linha, 4);
        
        txtCPF.setText(cpf);
        txtNome.setText(nome);
        txtSenha.setText(senha);
        txtEmail.setText(email);
        
        if (administrador == true) {
            radioSim.setSelected(true);
        } else {
            radioNao.setSelected(true);
        }
        
        

    }//GEN-LAST:event_tbConsultaUsuarioMouseClicked

    private void btnAlterarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarUsuarioMouseClicked
        // Alterando valores no banco de dados
        Connection con = Conexao.abrirConexao();
        
        UsuarioBean ub = new UsuarioBean();
        UsuarioDAO ud = new UsuarioDAO(con);
        
        ub.setCPF(txtCPF.getText());
        ub.setNome(txtNome.getText());
        ub.setSenha(txtSenha.getText());
        ub.setEmail(txtEmail.getText());
        
        if (radioSim.isSelected()) {
            ub.setAdministrador(true);
        } else {
            ub.setAdministrador(false);
        }
        
        lblMensagemUsuario.setText(ud.alterarUsuario(ub));
        
        Conexao.fecharConexao(con);

    }//GEN-LAST:event_btnAlterarUsuarioMouseClicked

    private void btnExcluirUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirUsuarioMouseClicked
        // Excluindo registros da tabela no bd.
        Connection con = Conexao.abrirConexao();
        
        UsuarioBean ub = new UsuarioBean();
        UsuarioDAO ud = new UsuarioDAO(con);
        
        ub.setCPF(txtCPF.getText());

        //Cria um vetor de Objetos passando a opção de sim ou não
        Object[] opcoes = {"Sim", "Não"};
        
        int i = JOptionPane.showOptionDialog(
                null,
                "Deseja excluir esse usuário: " + txtNome.getText() + "?",
                "Exclusão",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opcoes,
                opcoes[0]);
        
        if (i == JOptionPane.YES_OPTION) {
            lblMensagemUsuario.setText(ud.excluirUsuario(ub));
        }
        
        Conexao.fecharConexao(con);

    }//GEN-LAST:event_btnExcluirUsuarioMouseClicked

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void radioSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioSimActionPerformed

    private void radioNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioNaoActionPerformed

    private void btnIncluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIncluirUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarUsuario;
    private javax.swing.JButton btnExcluirUsuario;
    private javax.swing.JButton btnIncluirUsuario;
    private javax.swing.JButton btnLimparUsuario;
    private javax.swing.JButton btnListarUsuario;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCPF1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblMensagemUsuario;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBotoes;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlConsultaUsuario;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JRadioButton radioNao;
    private javax.swing.JRadioButton radioSim;
    private javax.swing.JTable tbConsultaUsuario;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
